### ISSUE TITLE
{% load staticfiles %} removed/depreciated

### ISSUE THREAD

**Issue by afarntrog** [leifos/tango_with_django_2#10]
If you use ` {% load staticfiles %}` in Django 3 you will get the following error: `'staticfiles' is not a registered tag library.`
This is because it was completely [removed](https://docs.djangoproject.com/en/dev/releases/3.0/#features-removed-in-3-0) in Django 3 and replaced with ` {% load static %}`
I know the book is for Django 2.x but this may be worth mentioning because it was **also** [deprecated](https://docs.djangoproject.com/en/2.2/releases/2.1/#features-deprecated-in-2-1) in Django 2.1, aside from being completely removed in 3.

The book is great,
Thank you.

**Comment by maxwelld90** [comment]
Hi @afarntrog!
Thanks for getting in touch. You're absolutely right. We were thinking about switching over for this current version, but just decided to keep things as they had been. For Django 3, we have it in our list of todo's when we get around to a new, updated version of TwD. Hopefully in a few months time. 🤠

Thanks for your kind words! Hope you are enjoying it.
Cheers,
David
