### ISSUE TITLE
Chapter 5: Outadated link

### ISSUE THREAD

**Issue by marshwiggle** [leifos/tango_with_django_2#3]
The link 'official Django documentation on the admin interface' points to the oudated version of Django.

**Comment by maxwelld90** [comment]
Hi @marshwiggle,
Many thanks for your input. Apologies for the delay in replying. I have fixed this, and the link now points to version 2.1 for the admin interface -- should be okay now.

Cheers,
David

**Comment by maxwelld90** [comment]
PS I have added your name to the acknowledgements of the book! :)
