### ISSUE TITLE
Bad name of the template

### ISSUE THREAD

**Issue by piotrsynowiec** [leifos/tango_with_django_2#4]
In chapter Bootstrapping Rango / Quick Style Change there's line:

_“Let’s apply these classes to our rango/categories.html template.”_

There's no such a file, and the file path should be **rango/cats** as is here: 
https://github.com/leifos/tango_with_django_2/tree/master/code/tango_with_django_project/templates/rango

**Comment by maxwelld90** [comment]
Thanks for your message!

I’m aware of this issue. Currently working through a revision of the book to address this inconsistency amongst others. The file that it is referring to is cats.html in the sample codebase.

Cheers,
David

**Comment by maxwelld90** [comment]
Problem fixed. Code and narrative now match up. Closing issue.
