### ISSUE TITLE
The chapter with custom template tags (for categories in sidebar) is repeated

### ISSUE THREAD

**Issue by piotrsynowiec** [leifos/tango_with_django_2#5]
Firstly it's in "Working with Templates" -> "Custom template tags". Then it's as a separate chapter after "Bootstrapping Rango".

**Comment by maxwelld90** [comment]
Hi Piotr,
Yeah, I saw this when I was going through my checks. Apologies about that. Problem solved. It's now only in the templates chapter.

Thanks for reporting this.
David
